project_id = "pcrxbfbktmekkkqhppjn"

[functions.qualify-entreprise]
verify_jwt = true

[functions.format-lead-details]
verify_jwt = true

[functions.send-email]
verify_jwt = false

[functions.send-welcome]
verify_jwt = false
