project_id = "pcrxbfbktmekkkqhppjn"

[functions.chat-tournee-assistant]
verify_jwt = false

[functions.qualify-all-entreprises]
verify_jwt = false

[functions.qualify-entreprises-background]
verify_jwt = true

[functions.qualify-subcategories]
verify_jwt = false

[functions.format-lead-details]
verify_jwt = true

[functions.send-email]
verify_jwt = false

[functions.send-welcome]
verify_jwt = false
