// Libellés officiels des sous-classes NAF (codes complets avec lettre finale)
// Source: INSEE NAF Rév. 2

export const NAF_SOUS_CLASSES: Record<string, { label: string; classe: string }> = {
  // Section A - Agriculture, sylviculture et pêche
  '01.11Z': { label: 'Culture de céréales (à l\'exception du riz), de légumineuses et de graines oléagineuses', classe: '01.11' },
  '01.12Z': { label: 'Culture du riz', classe: '01.12' },
  '01.13Z': { label: 'Culture de légumes, de melons, de racines et de tubercules', classe: '01.13' },
  '01.14Z': { label: 'Culture de la canne à sucre', classe: '01.14' },
  '01.15Z': { label: 'Culture du tabac', classe: '01.15' },
  '01.16Z': { label: 'Culture de plantes à fibres', classe: '01.16' },
  '01.19Z': { label: 'Autres cultures non permanentes', classe: '01.19' },
  '01.21Z': { label: 'Culture de la vigne', classe: '01.21' },
  '01.22Z': { label: 'Culture de fruits tropicaux et subtropicaux', classe: '01.22' },
  '01.23Z': { label: 'Culture d\'agrumes', classe: '01.23' },
  '01.24Z': { label: 'Culture de fruits à pépins et à noyau', classe: '01.24' },
  '01.25Z': { label: 'Culture d\'autres fruits d\'arbres ou d\'arbustes et de fruits à coque', classe: '01.25' },
  '01.26Z': { label: 'Culture de fruits oléagineux', classe: '01.26' },
  '01.27Z': { label: 'Culture de plantes à boissons', classe: '01.27' },
  '01.28Z': { label: 'Culture de plantes à épices, aromatiques, médicinales et pharmaceutiques', classe: '01.28' },
  '01.29Z': { label: 'Autres cultures permanentes', classe: '01.29' },
  '01.30Z': { label: 'Reproduction de plantes', classe: '01.30' },
  '01.41Z': { label: 'Élevage de vaches laitières', classe: '01.41' },
  '01.42Z': { label: 'Élevage d\'autres bovins et de buffles', classe: '01.42' },
  '01.43Z': { label: 'Élevage de chevaux et d\'autres équidés', classe: '01.43' },
  '01.44Z': { label: 'Élevage de chameaux et d\'autres camélidés', classe: '01.44' },
  '01.45Z': { label: 'Élevage d\'ovins et de caprins', classe: '01.45' },
  '01.46Z': { label: 'Élevage de porcins', classe: '01.46' },
  '01.47Z': { label: 'Élevage de volailles', classe: '01.47' },
  '01.49Z': { label: 'Élevage d\'autres animaux', classe: '01.49' },
  '01.50Z': { label: 'Culture et élevage associés', classe: '01.50' },
  '01.61Z': { label: 'Activités de soutien aux cultures', classe: '01.61' },
  '01.62Z': { label: 'Activités de soutien à la production animale', classe: '01.62' },
  '01.63Z': { label: 'Traitement primaire des récoltes', classe: '01.63' },
  '01.64Z': { label: 'Traitement des semences', classe: '01.64' },
  '01.70Z': { label: 'Chasse, piégeage et services annexes', classe: '01.70' },
  '02.10Z': { label: 'Sylviculture et autres activités forestières', classe: '02.10' },
  '02.20Z': { label: 'Exploitation forestière', classe: '02.20' },
  '02.30Z': { label: 'Récolte de produits forestiers non ligneux poussant à l\'état sauvage', classe: '02.30' },
  '02.40Z': { label: 'Services de soutien à l\'exploitation forestière', classe: '02.40' },
  '03.11Z': { label: 'Pêche en mer', classe: '03.11' },
  '03.12Z': { label: 'Pêche en eau douce', classe: '03.12' },
  '03.21Z': { label: 'Aquaculture en mer', classe: '03.21' },
  '03.22Z': { label: 'Aquaculture en eau douce', classe: '03.22' },

  // Section B - Industries extractives
  '05.10Z': { label: 'Extraction de houille', classe: '05.10' },
  '05.20Z': { label: 'Extraction de lignite', classe: '05.20' },
  '06.10Z': { label: 'Extraction de pétrole brut', classe: '06.10' },
  '06.20Z': { label: 'Extraction de gaz naturel', classe: '06.20' },
  '07.10Z': { label: 'Extraction de minerais de fer', classe: '07.10' },
  '07.21Z': { label: 'Extraction de minerais d\'uranium et de thorium', classe: '07.21' },
  '07.29Z': { label: 'Extraction d\'autres minerais de métaux non ferreux', classe: '07.29' },
  '08.11Z': { label: 'Extraction de pierres ornementales et de construction, de calcaire industriel, de gypse, de craie et d\'ardoise', classe: '08.11' },
  '08.12Z': { label: 'Exploitation de gravières et sablières, extraction d\'argiles et de kaolin', classe: '08.12' },
  '08.91Z': { label: 'Extraction des minéraux chimiques et d\'engrais minéraux', classe: '08.91' },
  '08.92Z': { label: 'Extraction de tourbe', classe: '08.92' },
  '08.93Z': { label: 'Production de sel', classe: '08.93' },
  '08.99Z': { label: 'Autres activités extractives n.c.a.', classe: '08.99' },
  '09.10Z': { label: 'Activités de soutien à l\'extraction d\'hydrocarbures', classe: '09.10' },
  '09.90Z': { label: 'Activités de soutien aux autres industries extractives', classe: '09.90' },

  // Section C - Industrie manufacturière
  '10.11Z': { label: 'Transformation et conservation de la viande de boucherie', classe: '10.11' },
  '10.12Z': { label: 'Transformation et conservation de la viande de volaille', classe: '10.12' },
  '10.13A': { label: 'Préparation industrielle de produits à base de viande', classe: '10.13' },
  '10.13B': { label: 'Charcuterie', classe: '10.13' },
  '10.20Z': { label: 'Transformation et conservation de poisson, de crustacés et de mollusques', classe: '10.20' },
  '10.31Z': { label: 'Transformation et conservation de pommes de terre', classe: '10.31' },
  '10.32Z': { label: 'Préparation de jus de fruits et légumes', classe: '10.32' },
  '10.39A': { label: 'Autre transformation et conservation de légumes', classe: '10.39' },
  '10.39B': { label: 'Transformation et conservation de fruits', classe: '10.39' },
  '10.41A': { label: 'Fabrication d\'huiles et graisses brutes', classe: '10.41' },
  '10.41B': { label: 'Fabrication d\'huiles et graisses raffinées', classe: '10.41' },
  '10.42Z': { label: 'Fabrication de margarine et graisses comestibles similaires', classe: '10.42' },
  '10.51A': { label: 'Fabrication de lait liquide et de produits frais', classe: '10.51' },
  '10.51B': { label: 'Fabrication de beurre', classe: '10.51' },
  '10.51C': { label: 'Fabrication de fromage', classe: '10.51' },
  '10.51D': { label: 'Fabrication d\'autres produits laitiers', classe: '10.51' },
  '10.52Z': { label: 'Fabrication de glaces et sorbets', classe: '10.52' },
  '10.61A': { label: 'Meunerie', classe: '10.61' },
  '10.61B': { label: 'Autres activités du travail des grains', classe: '10.61' },
  '10.62Z': { label: 'Fabrication de produits amylacés', classe: '10.62' },
  '10.71A': { label: 'Fabrication industrielle de pain et de pâtisserie fraîche', classe: '10.71' },
  '10.71B': { label: 'Cuisson de produits de boulangerie', classe: '10.71' },
  '10.71C': { label: 'Boulangerie et boulangerie-pâtisserie', classe: '10.71' },
  '10.71D': { label: 'Pâtisserie', classe: '10.71' },
  '10.72Z': { label: 'Fabrication de biscuits, biscottes et pâtisseries de conservation', classe: '10.72' },
  '10.73Z': { label: 'Fabrication de pâtes alimentaires', classe: '10.73' },
  '10.81Z': { label: 'Fabrication de sucre', classe: '10.81' },
  '10.82Z': { label: 'Fabrication de cacao, chocolat et de produits de confiserie', classe: '10.82' },
  '10.83Z': { label: 'Transformation du thé et du café', classe: '10.83' },
  '10.84Z': { label: 'Fabrication de condiments et assaisonnements', classe: '10.84' },
  '10.85Z': { label: 'Fabrication de plats préparés', classe: '10.85' },
  '10.86Z': { label: 'Fabrication d\'aliments homogénéisés et diététiques', classe: '10.86' },
  '10.89Z': { label: 'Fabrication d\'autres produits alimentaires n.c.a.', classe: '10.89' },
  '10.91Z': { label: 'Fabrication d\'aliments pour animaux de ferme', classe: '10.91' },
  '10.92Z': { label: 'Fabrication d\'aliments pour animaux de compagnie', classe: '10.92' },
  '11.01Z': { label: 'Production de boissons alcooliques distillées', classe: '11.01' },
  '11.02A': { label: 'Fabrication de vins effervescents', classe: '11.02' },
  '11.02B': { label: 'Vinification', classe: '11.02' },
  '11.03Z': { label: 'Fabrication de cidre et de vins de fruits', classe: '11.03' },
  '11.04Z': { label: 'Production d\'autres boissons fermentées non distillées', classe: '11.04' },
  '11.05Z': { label: 'Fabrication de bière', classe: '11.05' },
  '11.06Z': { label: 'Fabrication de malt', classe: '11.06' },
  '11.07A': { label: 'Industrie des eaux de table', classe: '11.07' },
  '11.07B': { label: 'Production de boissons rafraîchissantes', classe: '11.07' },
  '12.00Z': { label: 'Fabrication de produits à base de tabac', classe: '12.00' },
  '13.10Z': { label: 'Préparation de fibres textiles et filature', classe: '13.10' },
  '13.20Z': { label: 'Tissage', classe: '13.20' },
  '13.30Z': { label: 'Ennoblissement textile', classe: '13.30' },
  '13.91Z': { label: 'Fabrication d\'étoffes à mailles', classe: '13.91' },
  '13.92Z': { label: 'Fabrication d\'articles textiles, sauf habillement', classe: '13.92' },
  '13.93Z': { label: 'Fabrication de tapis et moquettes', classe: '13.93' },
  '13.94Z': { label: 'Fabrication de ficelles, cordes et filets', classe: '13.94' },
  '13.95Z': { label: 'Fabrication de non-tissés, sauf habillement', classe: '13.95' },
  '13.96Z': { label: 'Fabrication d\'autres textiles techniques et industriels', classe: '13.96' },
  '13.99Z': { label: 'Fabrication d\'autres textiles n.c.a.', classe: '13.99' },
  '14.11Z': { label: 'Fabrication de vêtements en cuir', classe: '14.11' },
  '14.12Z': { label: 'Fabrication de vêtements de travail', classe: '14.12' },
  '14.13Z': { label: 'Fabrication de vêtements de dessus', classe: '14.13' },
  '14.14Z': { label: 'Fabrication de vêtements de dessous', classe: '14.14' },
  '14.19Z': { label: 'Fabrication d\'autres vêtements et accessoires', classe: '14.19' },
  '14.20Z': { label: 'Fabrication d\'articles en fourrure', classe: '14.20' },
  '14.31Z': { label: 'Fabrication d\'articles chaussants à mailles', classe: '14.31' },
  '14.39Z': { label: 'Fabrication d\'autres articles à mailles', classe: '14.39' },
  '15.11Z': { label: 'Apprêt et tannage des cuirs ; préparation et teinture des fourrures', classe: '15.11' },
  '15.12Z': { label: 'Fabrication d\'articles de voyage, de maroquinerie et de sellerie', classe: '15.12' },
  '15.20Z': { label: 'Fabrication de chaussures', classe: '15.20' },
  '16.10A': { label: 'Sciage et rabotage du bois, hors imprégnation', classe: '16.10' },
  '16.10B': { label: 'Imprégnation du bois', classe: '16.10' },
  '16.21Z': { label: 'Fabrication de placage et de panneaux de bois', classe: '16.21' },
  '16.22Z': { label: 'Fabrication de parquets assemblés', classe: '16.22' },
  '16.23Z': { label: 'Fabrication de charpentes et d\'autres menuiseries', classe: '16.23' },
  '16.24Z': { label: 'Fabrication d\'emballages en bois', classe: '16.24' },
  '16.29Z': { label: 'Fabrication d\'objets divers en bois ; fabrication d\'objets en liège, vannerie et sparterie', classe: '16.29' },
  '17.11Z': { label: 'Fabrication de pâte à papier', classe: '17.11' },
  '17.12Z': { label: 'Fabrication de papier et de carton', classe: '17.12' },
  '17.21A': { label: 'Fabrication de carton ondulé', classe: '17.21' },
  '17.21B': { label: 'Fabrication de cartonnages', classe: '17.21' },
  '17.21C': { label: 'Fabrication d\'emballages en papier', classe: '17.21' },
  '17.22Z': { label: 'Fabrication d\'articles en papier à usage sanitaire ou domestique', classe: '17.22' },
  '17.23Z': { label: 'Fabrication d\'articles de papeterie', classe: '17.23' },
  '17.24Z': { label: 'Fabrication de papiers peints', classe: '17.24' },
  '17.29Z': { label: 'Fabrication d\'autres articles en papier ou en carton', classe: '17.29' },
  '18.11Z': { label: 'Imprimerie de journaux', classe: '18.11' },
  '18.12Z': { label: 'Autre imprimerie (labeur)', classe: '18.12' },
  '18.13Z': { label: 'Activités de pré-presse', classe: '18.13' },
  '18.14Z': { label: 'Reliure et activités connexes', classe: '18.14' },
  '18.20Z': { label: 'Reproduction d\'enregistrements', classe: '18.20' },
  '19.10Z': { label: 'Cokéfaction', classe: '19.10' },
  '19.20Z': { label: 'Raffinage du pétrole', classe: '19.20' },
  '20.11Z': { label: 'Fabrication de gaz industriels', classe: '20.11' },
  '20.12Z': { label: 'Fabrication de colorants et de pigments', classe: '20.12' },
  '20.13A': { label: 'Enrichissement et retraitement de matières nucléaires', classe: '20.13' },
  '20.13B': { label: 'Fabrication d\'autres produits chimiques inorganiques de base n.c.a.', classe: '20.13' },
  '20.14Z': { label: 'Fabrication d\'autres produits chimiques organiques de base', classe: '20.14' },
  '20.15Z': { label: 'Fabrication de produits azotés et d\'engrais', classe: '20.15' },
  '20.16Z': { label: 'Fabrication de matières plastiques de base', classe: '20.16' },
  '20.17Z': { label: 'Fabrication de caoutchouc synthétique', classe: '20.17' },
  '20.20Z': { label: 'Fabrication de pesticides et d\'autres produits agrochimiques', classe: '20.20' },
  '20.30Z': { label: 'Fabrication de peintures, vernis, encres et mastics', classe: '20.30' },
  '20.41Z': { label: 'Fabrication de savons, détergents et produits d\'entretien', classe: '20.41' },
  '20.42Z': { label: 'Fabrication de parfums et de produits pour la toilette', classe: '20.42' },
  '20.51Z': { label: 'Fabrication de produits explosifs', classe: '20.51' },
  '20.52Z': { label: 'Fabrication de colles', classe: '20.52' },
  '20.53Z': { label: 'Fabrication d\'huiles essentielles', classe: '20.53' },
  '20.59Z': { label: 'Fabrication d\'autres produits chimiques n.c.a.', classe: '20.59' },
  '20.60Z': { label: 'Fabrication de fibres artificielles ou synthétiques', classe: '20.60' },
  '21.10Z': { label: 'Fabrication de produits pharmaceutiques de base', classe: '21.10' },
  '21.20Z': { label: 'Fabrication de préparations pharmaceutiques', classe: '21.20' },
  '22.11Z': { label: 'Fabrication et rechapage de pneumatiques', classe: '22.11' },
  '22.19Z': { label: 'Fabrication d\'autres articles en caoutchouc', classe: '22.19' },
  '22.21Z': { label: 'Fabrication de plaques, feuilles, tubes et profilés en matières plastiques', classe: '22.21' },
  '22.22Z': { label: 'Fabrication d\'emballages en matières plastiques', classe: '22.22' },
  '22.23Z': { label: 'Fabrication d\'éléments en matières plastiques pour la construction', classe: '22.23' },
  '22.29A': { label: 'Fabrication de pièces techniques à base de matières plastiques', classe: '22.29' },
  '22.29B': { label: 'Fabrication de produits de consommation courante en matières plastiques', classe: '22.29' },
  '23.11Z': { label: 'Fabrication de verre plat', classe: '23.11' },
  '23.12Z': { label: 'Façonnage et transformation du verre plat', classe: '23.12' },
  '23.13Z': { label: 'Fabrication de verre creux', classe: '23.13' },
  '23.14Z': { label: 'Fabrication de fibres de verre', classe: '23.14' },
  '23.19Z': { label: 'Fabrication et façonnage d\'autres articles en verre, y compris verre technique', classe: '23.19' },
  '23.20Z': { label: 'Fabrication de produits réfractaires', classe: '23.20' },
  '23.31Z': { label: 'Fabrication de carreaux en céramique', classe: '23.31' },
  '23.32Z': { label: 'Fabrication de briques, tuiles et produits de construction, en terre cuite', classe: '23.32' },
  '23.41Z': { label: 'Fabrication d\'articles céramiques à usage domestique ou ornemental', classe: '23.41' },
  '23.42Z': { label: 'Fabrication d\'appareils sanitaires en céramique', classe: '23.42' },
  '23.43Z': { label: 'Fabrication d\'isolateurs et pièces isolantes en céramique', classe: '23.43' },
  '23.44Z': { label: 'Fabrication d\'autres produits céramiques à usage technique', classe: '23.44' },
  '23.49Z': { label: 'Fabrication d\'autres produits céramiques', classe: '23.49' },
  '23.51Z': { label: 'Fabrication de ciment', classe: '23.51' },
  '23.52Z': { label: 'Fabrication de chite et plâtre', classe: '23.52' },
  '23.61Z': { label: 'Fabrication d\'éléments en béton pour la construction', classe: '23.61' },
  '23.62Z': { label: 'Fabrication d\'éléments en plâtre pour la construction', classe: '23.62' },
  '23.63Z': { label: 'Fabrication de béton prêt à l\'emploi', classe: '23.63' },
  '23.64Z': { label: 'Fabrication de mortiers et bétons secs', classe: '23.64' },
  '23.65Z': { label: 'Fabrication d\'ouvrages en fibre-ciment', classe: '23.65' },
  '23.69Z': { label: 'Fabrication d\'autres ouvrages en béton, en ciment ou en plâtre', classe: '23.69' },
  '23.70Z': { label: 'Taille, façonnage et finissage de pierres', classe: '23.70' },
  '23.91Z': { label: 'Fabrication de produits abrasifs', classe: '23.91' },
  '23.99Z': { label: 'Fabrication d\'autres produits minéraux non métalliques n.c.a.', classe: '23.99' },
  '24.10Z': { label: 'Sidérurgie', classe: '24.10' },
  '24.20Z': { label: 'Fabrication de tubes, tuyaux, profilés creux et accessoires correspondants en acier', classe: '24.20' },
  '24.31Z': { label: 'Étirage à froid de barres', classe: '24.31' },
  '24.32Z': { label: 'Laminage à froid de feuillards', classe: '24.32' },
  '24.33Z': { label: 'Profilage à froid par formage ou pliage', classe: '24.33' },
  '24.34Z': { label: 'Tréfilage à froid', classe: '24.34' },
  '24.41Z': { label: 'Production de métaux précieux', classe: '24.41' },
  '24.42Z': { label: 'Métallurgie de l\'aluminium', classe: '24.42' },
  '24.43Z': { label: 'Métallurgie du plomb, du zinc ou de l\'étain', classe: '24.43' },
  '24.44Z': { label: 'Métallurgie du cuivre', classe: '24.44' },
  '24.45Z': { label: 'Métallurgie des autres métaux non ferreux', classe: '24.45' },
  '24.46Z': { label: 'Élaboration et transformation de matières nucléaires', classe: '24.46' },
  '24.51Z': { label: 'Fonderie de fonte', classe: '24.51' },
  '24.52Z': { label: 'Fonderie d\'acier', classe: '24.52' },
  '24.53Z': { label: 'Fonderie de métaux légers', classe: '24.53' },
  '24.54Z': { label: 'Fonderie d\'autres métaux non ferreux', classe: '24.54' },
  '25.11Z': { label: 'Fabrication de structures métalliques et de parties de structures', classe: '25.11' },
  '25.12Z': { label: 'Fabrication de portes et fenêtres en métal', classe: '25.12' },
  '25.21Z': { label: 'Fabrication de radiateurs et de chaudières pour le chauffage central', classe: '25.21' },
  '25.29Z': { label: 'Fabrication d\'autres réservoirs, citernes et conteneurs métalliques', classe: '25.29' },
  '25.30Z': { label: 'Fabrication de générateurs de vapeur, à l\'exception des chaudières pour le chauffage central', classe: '25.30' },
  '25.40Z': { label: 'Fabrication d\'armes et de munitions', classe: '25.40' },
  '25.50A': { label: 'Forge, estampage, matriçage ; métallurgie des poudres', classe: '25.50' },
  '25.50B': { label: 'Découpage, emboutissage', classe: '25.50' },
  '25.61Z': { label: 'Traitement et revêtement des métaux', classe: '25.61' },
  '25.62A': { label: 'Décolletage', classe: '25.62' },
  '25.62B': { label: 'Mécanique industrielle', classe: '25.62' },
  '25.71Z': { label: 'Fabrication de coutellerie', classe: '25.71' },
  '25.72Z': { label: 'Fabrication de serrures et de ferrures', classe: '25.72' },
  '25.73A': { label: 'Fabrication de moules et modèles', classe: '25.73' },
  '25.73B': { label: 'Fabrication d\'autres outillages', classe: '25.73' },
  '25.91Z': { label: 'Fabrication de fûts et emballages métalliques similaires', classe: '25.91' },
  '25.92Z': { label: 'Fabrication d\'emballages métalliques légers', classe: '25.92' },
  '25.93Z': { label: 'Fabrication d\'articles en fils métalliques, de chaînes et de ressorts', classe: '25.93' },
  '25.94Z': { label: 'Fabrication de vis et de boulons', classe: '25.94' },
  '25.99A': { label: 'Fabrication d\'articles métalliques ménagers', classe: '25.99' },
  '25.99B': { label: 'Fabrication d\'autres articles métalliques', classe: '25.99' },
  '26.11Z': { label: 'Fabrication de composants électroniques', classe: '26.11' },
  '26.12Z': { label: 'Fabrication de cartes électroniques assemblées', classe: '26.12' },
  '26.20Z': { label: 'Fabrication d\'ordinateurs et d\'équipements périphériques', classe: '26.20' },
  '26.30Z': { label: 'Fabrication d\'équipements de communication', classe: '26.30' },
  '26.40Z': { label: 'Fabrication de produits électroniques grand public', classe: '26.40' },
  '26.51A': { label: 'Fabrication d\'équipements d\'aide à la navigation', classe: '26.51' },
  '26.51B': { label: 'Fabrication d\'instrumentation scientifique et technique', classe: '26.51' },
  '26.52Z': { label: 'Horlogerie', classe: '26.52' },
  '26.60Z': { label: 'Fabrication d\'équipements d\'irradiation médicale, d\'équipements électromédicaux et électrothérapeutiques', classe: '26.60' },
  '26.70Z': { label: 'Fabrication de matériels optique et photographique', classe: '26.70' },
  '26.80Z': { label: 'Fabrication de supports magnétiques et optiques', classe: '26.80' },
  '27.11Z': { label: 'Fabrication de moteurs, génératrices et transformateurs électriques', classe: '27.11' },
  '27.12Z': { label: 'Fabrication de matériel de distribution et de commande électrique', classe: '27.12' },
  '27.20Z': { label: 'Fabrication de piles et d\'accumulateurs électriques', classe: '27.20' },
  '27.31Z': { label: 'Fabrication de câbles de fibres optiques', classe: '27.31' },
  '27.32Z': { label: 'Fabrication d\'autres fils et câbles électroniques ou électriques', classe: '27.32' },
  '27.33Z': { label: 'Fabrication de matériel d\'installation électrique', classe: '27.33' },
  '27.40Z': { label: 'Fabrication d\'appareils d\'éclairage électrique', classe: '27.40' },
  '27.51Z': { label: 'Fabrication d\'appareils électroménagers', classe: '27.51' },
  '27.52Z': { label: 'Fabrication d\'appareils ménagers non électriques', classe: '27.52' },
  '27.90Z': { label: 'Fabrication d\'autres matériels électriques', classe: '27.90' },
  '28.11Z': { label: 'Fabrication de moteurs et turbines, à l\'exception des moteurs d\'avions et de véhicules', classe: '28.11' },
  '28.12Z': { label: 'Fabrication d\'équipements hydrauliques et pneumatiques', classe: '28.12' },
  '28.13Z': { label: 'Fabrication d\'autres pompes et compresseurs', classe: '28.13' },
  '28.14Z': { label: 'Fabrication d\'autres articles de robinetterie', classe: '28.14' },
  '28.15Z': { label: 'Fabrication d\'engrenages et d\'organes mécaniques de transmission', classe: '28.15' },
  '28.21Z': { label: 'Fabrication de fours et brûleurs', classe: '28.21' },
  '28.22Z': { label: 'Fabrication de matériel de levage et de manutention', classe: '28.22' },
  '28.23Z': { label: 'Fabrication de machines et d\'équipements de bureau (à l\'exception des ordinateurs et équipements périphériques)', classe: '28.23' },
  '28.24Z': { label: 'Fabrication d\'outillage portatif à moteur incorporé', classe: '28.24' },
  '28.25Z': { label: 'Fabrication d\'équipements aérauliques et frigorifiques industriels', classe: '28.25' },
  '28.29A': { label: 'Fabrication d\'équipements d\'emballage, de conditionnement et de pesage', classe: '28.29' },
  '28.29B': { label: 'Fabrication d\'autres machines d\'usage général', classe: '28.29' },
  '28.30Z': { label: 'Fabrication de machines agricoles et forestières', classe: '28.30' },
  '28.41Z': { label: 'Fabrication de machines-outils pour le travail des métaux', classe: '28.41' },
  '28.49Z': { label: 'Fabrication d\'autres machines-outils', classe: '28.49' },
  '28.91Z': { label: 'Fabrication de machines pour la métallurgie', classe: '28.91' },
  '28.92Z': { label: 'Fabrication de machines pour l\'extraction ou la construction', classe: '28.92' },
  '28.93Z': { label: 'Fabrication de machines pour l\'industrie agro-alimentaire', classe: '28.93' },
  '28.94Z': { label: 'Fabrication de machines pour les industries textiles', classe: '28.94' },
  '28.95Z': { label: 'Fabrication de machines pour les industries du papier et du carton', classe: '28.95' },
  '28.96Z': { label: 'Fabrication de machines pour le travail du caoutchouc ou des plastiques', classe: '28.96' },
  '28.99A': { label: 'Fabrication de machines d\'imprimerie', classe: '28.99' },
  '28.99B': { label: 'Fabrication d\'autres machines spécialisées', classe: '28.99' },
  '29.10Z': { label: 'Construction de véhicules automobiles', classe: '29.10' },
  '29.20Z': { label: 'Fabrication de carrosseries et remorques', classe: '29.20' },
  '29.31Z': { label: 'Fabrication d\'équipements électriques et électroniques automobiles', classe: '29.31' },
  '29.32Z': { label: 'Fabrication d\'autres équipements automobiles', classe: '29.32' },
  '30.11Z': { label: 'Construction de navires et de structures flottantes', classe: '30.11' },
  '30.12Z': { label: 'Construction de bateaux de plaisance', classe: '30.12' },
  '30.20Z': { label: 'Construction de locomotives et d\'autre matériel ferroviaire roulant', classe: '30.20' },
  '30.30Z': { label: 'Construction aéronautique et spatiale', classe: '30.30' },
  '30.40Z': { label: 'Construction de véhicules militaires de combat', classe: '30.40' },
  '30.91Z': { label: 'Fabrication de motocycles', classe: '30.91' },
  '30.92Z': { label: 'Fabrication de bicyclettes et de véhicules pour invalides', classe: '30.92' },
  '30.99Z': { label: 'Fabrication d\'autres équipements de transport n.c.a.', classe: '30.99' },
  '31.01Z': { label: 'Fabrication de meubles de bureau et de magasin', classe: '31.01' },
  '31.02Z': { label: 'Fabrication de meubles de cuisine', classe: '31.02' },
  '31.03Z': { label: 'Fabrication de matelas', classe: '31.03' },
  '31.09A': { label: 'Fabrication de sièges d\'ameublement d\'intérieur', classe: '31.09' },
  '31.09B': { label: 'Fabrication d\'autres meubles et industries connexes de l\'ameublement', classe: '31.09' },
  '32.11Z': { label: 'Frappe de monnaie', classe: '32.11' },
  '32.12Z': { label: 'Fabrication d\'articles de joaillerie et bijouterie', classe: '32.12' },
  '32.13Z': { label: 'Fabrication d\'articles de bijouterie fantaisie et articles similaires', classe: '32.13' },
  '32.20Z': { label: 'Fabrication d\'instruments de musique', classe: '32.20' },
  '32.30Z': { label: 'Fabrication d\'articles de sport', classe: '32.30' },
  '32.40Z': { label: 'Fabrication de jeux et jouets', classe: '32.40' },
  '32.50A': { label: 'Fabrication de matériel médico-chirurgical et dentaire', classe: '32.50' },
  '32.50B': { label: 'Fabrication de lunettes', classe: '32.50' },
  '32.91Z': { label: 'Fabrication d\'articles de brosserie', classe: '32.91' },
  '32.99Z': { label: 'Autres activités manufacturières n.c.a.', classe: '32.99' },
  '33.11Z': { label: 'Réparation d\'ouvrages en métaux', classe: '33.11' },
  '33.12Z': { label: 'Réparation de machines et équipements mécaniques', classe: '33.12' },
  '33.13Z': { label: 'Réparation de matériels électroniques et optiques', classe: '33.13' },
  '33.14Z': { label: 'Réparation d\'équipements électriques', classe: '33.14' },
  '33.15Z': { label: 'Réparation et maintenance navale', classe: '33.15' },
  '33.16Z': { label: 'Réparation et maintenance d\'aéronefs et d\'engins spatiaux', classe: '33.16' },
  '33.17Z': { label: 'Réparation et maintenance d\'autres équipements de transport', classe: '33.17' },
  '33.19Z': { label: 'Réparation d\'autres équipements', classe: '33.19' },
  '33.20A': { label: 'Installation de structures métalliques, chaudronnées et de tuyauterie', classe: '33.20' },
  '33.20B': { label: 'Installation de machines et équipements mécaniques', classe: '33.20' },
  '33.20C': { label: 'Conception d\'ensemble et assemblage sur site industriel d\'équipements de contrôle des processus industriels', classe: '33.20' },
  '33.20D': { label: 'Installation d\'équipements électriques, de matériels électroniques et optiques ou d\'autres matériels', classe: '33.20' },

  // Section D - Production et distribution d'électricité, de gaz
  '35.11Z': { label: 'Production d\'électricité', classe: '35.11' },
  '35.12Z': { label: 'Transport d\'électricité', classe: '35.12' },
  '35.13Z': { label: 'Distribution d\'électricité', classe: '35.13' },
  '35.14Z': { label: 'Commerce d\'électricité', classe: '35.14' },
  '35.21Z': { label: 'Production de combustibles gazeux', classe: '35.21' },
  '35.22Z': { label: 'Distribution de combustibles gazeux par conduites', classe: '35.22' },
  '35.23Z': { label: 'Commerce de combustibles gazeux par conduites', classe: '35.23' },
  '35.30Z': { label: 'Production et distribution de vapeur et d\'air conditionné', classe: '35.30' },

  // Section E - Production et distribution d'eau ; assainissement
  '36.00Z': { label: 'Captage, traitement et distribution d\'eau', classe: '36.00' },
  '37.00Z': { label: 'Collecte et traitement des eaux usées', classe: '37.00' },
  '38.11Z': { label: 'Collecte des déchets non dangereux', classe: '38.11' },
  '38.12Z': { label: 'Collecte des déchets dangereux', classe: '38.12' },
  '38.21Z': { label: 'Traitement et élimination des déchets non dangereux', classe: '38.21' },
  '38.22Z': { label: 'Traitement et élimination des déchets dangereux', classe: '38.22' },
  '38.31Z': { label: 'Démantèlement d\'épaves', classe: '38.31' },
  '38.32Z': { label: 'Récupération de déchets triés', classe: '38.32' },
  '39.00Z': { label: 'Dépollution et autres services de gestion des déchets', classe: '39.00' },

  // Section F - Construction
  '41.10Z': { label: 'Promotion immobilière', classe: '41.10' },
  '41.20A': { label: 'Construction de maisons individuelles', classe: '41.20' },
  '41.20B': { label: 'Construction d\'autres bâtiments', classe: '41.20' },
  '42.11Z': { label: 'Construction de routes et autoroutes', classe: '42.11' },
  '42.12Z': { label: 'Construction de voies ferrées de surface et souterraines', classe: '42.12' },
  '42.13A': { label: 'Construction d\'ouvrages d\'art', classe: '42.13' },
  '42.13B': { label: 'Construction et entretien de tunnels', classe: '42.13' },
  '42.21Z': { label: 'Construction de réseaux pour fluides', classe: '42.21' },
  '42.22Z': { label: 'Construction de réseaux électriques et de télécommunications', classe: '42.22' },
  '42.91Z': { label: 'Construction d\'ouvrages maritimes et fluviaux', classe: '42.91' },
  '42.99Z': { label: 'Construction d\'autres ouvrages de génie civil n.c.a.', classe: '42.99' },
  '43.11Z': { label: 'Travaux de démolition', classe: '43.11' },
  '43.12A': { label: 'Travaux de terrassement courants et travaux préparatoires', classe: '43.12' },
  '43.12B': { label: 'Travaux de terrassement spécialisés ou de grande masse', classe: '43.12' },
  '43.13Z': { label: 'Forages et sondages', classe: '43.13' },
  '43.21A': { label: 'Travaux d\'installation électrique dans tous locaux', classe: '43.21' },
  '43.21B': { label: 'Travaux d\'installation électrique sur la voie publique', classe: '43.21' },
  '43.22A': { label: 'Travaux d\'installation d\'eau et de gaz en tous locaux', classe: '43.22' },
  '43.22B': { label: 'Travaux d\'installation d\'équipements thermiques et de climatisation', classe: '43.22' },
  '43.29A': { label: 'Travaux d\'isolation', classe: '43.29' },
  '43.29B': { label: 'Autres travaux d\'installation n.c.a.', classe: '43.29' },
  '43.31Z': { label: 'Travaux de plâtrerie', classe: '43.31' },
  '43.32A': { label: 'Travaux de menuiserie bois et PVC', classe: '43.32' },
  '43.32B': { label: 'Travaux de menuiserie métallique et serrurerie', classe: '43.32' },
  '43.32C': { label: 'Agencement de lieux de vente', classe: '43.32' },
  '43.33Z': { label: 'Travaux de revêtement des sols et des murs', classe: '43.33' },
  '43.34Z': { label: 'Travaux de peinture et vitrerie', classe: '43.34' },
  '43.39Z': { label: 'Autres travaux de finition', classe: '43.39' },
  '43.91A': { label: 'Travaux de charpente', classe: '43.91' },
  '43.91B': { label: 'Travaux de couverture par éléments', classe: '43.91' },
  '43.99A': { label: 'Travaux d\'étanchéification', classe: '43.99' },
  '43.99B': { label: 'Travaux de montage de structures métalliques', classe: '43.99' },
  '43.99C': { label: 'Travaux de maçonnerie générale et gros œuvre de bâtiment', classe: '43.99' },
  '43.99D': { label: 'Autres travaux spécialisés de construction', classe: '43.99' },
  '43.99E': { label: 'Location avec opérateur de matériel de construction', classe: '43.99' },

  // Section G - Commerce ; réparation d'automobiles et de motocycles
  '45.11Z': { label: 'Commerce de voitures et de véhicules automobiles légers', classe: '45.11' },
  '45.19Z': { label: 'Commerce d\'autres véhicules automobiles', classe: '45.19' },
  '45.20A': { label: 'Entretien et réparation de véhicules automobiles légers', classe: '45.20' },
  '45.20B': { label: 'Entretien et réparation d\'autres véhicules automobiles', classe: '45.20' },
  '45.31Z': { label: 'Commerce de gros d\'équipements automobiles', classe: '45.31' },
  '45.32Z': { label: 'Commerce de détail d\'équipements automobiles', classe: '45.32' },
  '45.40Z': { label: 'Commerce et réparation de motocycles', classe: '45.40' },
  '46.11Z': { label: 'Intermédiaires du commerce en matières premières agricoles, animaux vivants, matières premières textiles et produits semi-finis', classe: '46.11' },
  '46.12A': { label: 'Centrales d\'achat de carburant', classe: '46.12' },
  '46.12B': { label: 'Autres intermédiaires du commerce en combustibles, métaux, minéraux et produits chimiques', classe: '46.12' },
  '46.13Z': { label: 'Intermédiaires du commerce en bois et matériaux de construction', classe: '46.13' },
  '46.14Z': { label: 'Intermédiaires du commerce en machines, équipements industriels, navires et avions', classe: '46.14' },
  '46.15Z': { label: 'Intermédiaires du commerce en meubles, articles de ménage et quincaillerie', classe: '46.15' },
  '46.16Z': { label: 'Intermédiaires du commerce en textiles, habillement, fourrures, chaussures et articles en cuir', classe: '46.16' },
  '46.17A': { label: 'Centrales d\'achat alimentaires', classe: '46.17' },
  '46.17B': { label: 'Autres intermédiaires du commerce en denrées, boissons et tabac', classe: '46.17' },
  '46.18Z': { label: 'Intermédiaires spécialisés dans le commerce d\'autres produits spécifiques', classe: '46.18' },
  '46.19A': { label: 'Centrales d\'achat non alimentaires', classe: '46.19' },
  '46.19B': { label: 'Autres intermédiaires du commerce en produits divers', classe: '46.19' },
  '46.21Z': { label: 'Commerce de gros de céréales, de tabac non manufacturé, de semences et d\'aliments pour le bétail', classe: '46.21' },
  '46.22Z': { label: 'Commerce de gros de fleurs et plantes', classe: '46.22' },
  '46.23Z': { label: 'Commerce de gros d\'animaux vivants', classe: '46.23' },
  '46.24Z': { label: 'Commerce de gros de cuirs et peaux', classe: '46.24' },
  '46.31Z': { label: 'Commerce de gros de fruits et légumes', classe: '46.31' },
  '46.32A': { label: 'Commerce de gros de viandes de boucherie', classe: '46.32' },
  '46.32B': { label: 'Commerce de gros de produits à base de viande', classe: '46.32' },
  '46.32C': { label: 'Commerce de gros de volailles et gibier', classe: '46.32' },
  '46.33Z': { label: 'Commerce de gros de produits laitiers, œufs, huiles et matières grasses comestibles', classe: '46.33' },
  '46.34Z': { label: 'Commerce de gros de boissons', classe: '46.34' },
  '46.35Z': { label: 'Commerce de gros de produits à base de tabac', classe: '46.35' },
  '46.36Z': { label: 'Commerce de gros de sucre, chocolat et confiserie', classe: '46.36' },
  '46.37Z': { label: 'Commerce de gros de café, thé, cacao et épices', classe: '46.37' },
  '46.38A': { label: 'Commerce de gros de poissons, crustacés et mollusques', classe: '46.38' },
  '46.38B': { label: 'Commerce de gros alimentaire spécialisé divers', classe: '46.38' },
  '46.39A': { label: 'Commerce de gros de produits surgelés', classe: '46.39' },
  '46.39B': { label: 'Commerce de gros alimentaire non spécialisé', classe: '46.39' },
  '46.41Z': { label: 'Commerce de gros de textiles', classe: '46.41' },
  '46.42Z': { label: 'Commerce de gros d\'habillement et de chaussures', classe: '46.42' },
  '46.43Z': { label: 'Commerce de gros d\'appareils électroménagers', classe: '46.43' },
  '46.44Z': { label: 'Commerce de gros de vaisselle, verrerie et produits d\'entretien', classe: '46.44' },
  '46.45Z': { label: 'Commerce de gros de parfumerie et de produits de beauté', classe: '46.45' },
  '46.46Z': { label: 'Commerce de gros de produits pharmaceutiques', classe: '46.46' },
  '46.47Z': { label: 'Commerce de gros de meubles, de tapis et d\'appareils d\'éclairage', classe: '46.47' },
  '46.48Z': { label: 'Commerce de gros d\'articles d\'horlogerie et de bijouterie', classe: '46.48' },
  '46.49Z': { label: 'Commerce de gros d\'autres biens domestiques', classe: '46.49' },
  '46.51Z': { label: 'Commerce de gros d\'ordinateurs, d\'équipements informatiques périphériques et de logiciels', classe: '46.51' },
  '46.52Z': { label: 'Commerce de gros de composants et d\'équipements électroniques et de télécommunication', classe: '46.52' },
  '46.61Z': { label: 'Commerce de gros de matériel agricole', classe: '46.61' },
  '46.62Z': { label: 'Commerce de gros de machines-outils', classe: '46.62' },
  '46.63Z': { label: 'Commerce de gros de machines pour l\'extraction, la construction et le génie civil', classe: '46.63' },
  '46.64Z': { label: 'Commerce de gros de machines pour l\'industrie textile et l\'habillement', classe: '46.64' },
  '46.65Z': { label: 'Commerce de gros de mobilier de bureau', classe: '46.65' },
  '46.66Z': { label: 'Commerce de gros d\'autres machines et équipements de bureau', classe: '46.66' },
  '46.69A': { label: 'Commerce de gros de matériel électrique', classe: '46.69' },
  '46.69B': { label: 'Commerce de gros de fournitures et équipements industriels divers', classe: '46.69' },
  '46.69C': { label: 'Commerce de gros de fournitures et équipements divers pour le commerce et les services', classe: '46.69' },
  '46.71Z': { label: 'Commerce de gros de combustibles et de produits annexes', classe: '46.71' },
  '46.72Z': { label: 'Commerce de gros de minerais et métaux', classe: '46.72' },
  '46.73A': { label: 'Commerce de gros de bois et de matériaux de construction', classe: '46.73' },
  '46.73B': { label: 'Commerce de gros d\'appareils sanitaires et de produits de décoration', classe: '46.73' },
  '46.74A': { label: 'Commerce de gros de quincaillerie', classe: '46.74' },
  '46.74B': { label: 'Commerce de gros de fournitures pour la plomberie et le chauffage', classe: '46.74' },
  '46.75Z': { label: 'Commerce de gros de produits chimiques', classe: '46.75' },
  '46.76Z': { label: 'Commerce de gros d\'autres produits intermédiaires', classe: '46.76' },
  '46.77Z': { label: 'Commerce de gros de déchets et débris', classe: '46.77' },
  '46.90Z': { label: 'Commerce de gros non spécialisé', classe: '46.90' },
  '47.11A': { label: 'Commerce de détail de produits surgelés', classe: '47.11' },
  '47.11B': { label: 'Commerce d\'alimentation générale', classe: '47.11' },
  '47.11C': { label: 'Supérettes', classe: '47.11' },
  '47.11D': { label: 'Supermarchés', classe: '47.11' },
  '47.11E': { label: 'Magasins multi-commerces', classe: '47.11' },
  '47.11F': { label: 'Hypermarchés', classe: '47.11' },
  '47.19A': { label: 'Grands magasins', classe: '47.19' },
  '47.19B': { label: 'Autres commerces de détail en magasin non spécialisé', classe: '47.19' },
  '47.21Z': { label: 'Commerce de détail de fruits et légumes en magasin spécialisé', classe: '47.21' },
  '47.22Z': { label: 'Commerce de détail de viandes et de produits à base de viande en magasin spécialisé', classe: '47.22' },
  '47.23Z': { label: 'Commerce de détail de poissons, crustacés et mollusques en magasin spécialisé', classe: '47.23' },
  '47.24Z': { label: 'Commerce de détail de pain, pâtisserie et confiserie en magasin spécialisé', classe: '47.24' },
  '47.25Z': { label: 'Commerce de détail de boissons en magasin spécialisé', classe: '47.25' },
  '47.26Z': { label: 'Commerce de détail de produits à base de tabac en magasin spécialisé', classe: '47.26' },
  '47.29Z': { label: 'Autres commerces de détail alimentaires en magasin spécialisé', classe: '47.29' },
  '47.30Z': { label: 'Commerce de détail de carburants en magasin spécialisé', classe: '47.30' },
  '47.41Z': { label: 'Commerce de détail d\'ordinateurs, d\'unités périphériques et de logiciels en magasin spécialisé', classe: '47.41' },
  '47.42Z': { label: 'Commerce de détail de matériels de télécommunication en magasin spécialisé', classe: '47.42' },
  '47.43Z': { label: 'Commerce de détail de matériels audio et vidéo en magasin spécialisé', classe: '47.43' },
  '47.51Z': { label: 'Commerce de détail de textiles en magasin spécialisé', classe: '47.51' },
  '47.52A': { label: 'Commerce de détail de quincaillerie, peintures et verres en petites surfaces (moins de 400 m²)', classe: '47.52' },
  '47.52B': { label: 'Commerce de détail de quincaillerie, peintures et verres en grandes surfaces (400 m² et plus)', classe: '47.52' },
  '47.53Z': { label: 'Commerce de détail de tapis, moquettes et revêtements de murs et de sols en magasin spécialisé', classe: '47.53' },
  '47.54Z': { label: 'Commerce de détail d\'appareils électroménagers en magasin spécialisé', classe: '47.54' },
  '47.59A': { label: 'Commerce de détail de meubles', classe: '47.59' },
  '47.59B': { label: 'Commerce de détail d\'autres équipements du foyer', classe: '47.59' },
  '47.61Z': { label: 'Commerce de détail de livres en magasin spécialisé', classe: '47.61' },
  '47.62Z': { label: 'Commerce de détail de journaux et papeterie en magasin spécialisé', classe: '47.62' },
  '47.63Z': { label: 'Commerce de détail d\'enregistrements musicaux et vidéo en magasin spécialisé', classe: '47.63' },
  '47.64Z': { label: 'Commerce de détail d\'articles de sport en magasin spécialisé', classe: '47.64' },
  '47.65Z': { label: 'Commerce de détail de jeux et jouets en magasin spécialisé', classe: '47.65' },
  '47.71Z': { label: 'Commerce de détail d\'habillement en magasin spécialisé', classe: '47.71' },
  '47.72A': { label: 'Commerce de détail de la chaussure', classe: '47.72' },
  '47.72B': { label: 'Commerce de détail de maroquinerie et d\'articles de voyage', classe: '47.72' },
  '47.73Z': { label: 'Commerce de détail de produits pharmaceutiques en magasin spécialisé', classe: '47.73' },
  '47.74Z': { label: 'Commerce de détail d\'articles médicaux et orthopédiques en magasin spécialisé', classe: '47.74' },
  '47.75Z': { label: 'Commerce de détail de parfumerie et de produits de beauté en magasin spécialisé', classe: '47.75' },
  '47.76Z': { label: 'Commerce de détail de fleurs, plantes, graines, engrais, animaux de compagnie et aliments pour ces animaux en magasin spécialisé', classe: '47.76' },
  '47.77Z': { label: 'Commerce de détail d\'articles d\'horlogerie et de bijouterie en magasin spécialisé', classe: '47.77' },
  '47.78A': { label: 'Commerces de détail d\'optique', classe: '47.78' },
  '47.78B': { label: 'Commerces de détail de charbons et combustibles', classe: '47.78' },
  '47.78C': { label: 'Autres commerces de détail spécialisés divers', classe: '47.78' },
  '47.79Z': { label: 'Commerce de détail de biens d\'occasion en magasin', classe: '47.79' },
  '47.81Z': { label: 'Commerce de détail alimentaire sur éventaires et marchés', classe: '47.81' },
  '47.82Z': { label: 'Commerce de détail de textiles, d\'habillement et de chaussures sur éventaires et marchés', classe: '47.82' },
  '47.89Z': { label: 'Autres commerces de détail sur éventaires et marchés', classe: '47.89' },
  '47.91A': { label: 'Vente à distance sur catalogue général', classe: '47.91' },
  '47.91B': { label: 'Vente à distance sur catalogue spécialisé', classe: '47.91' },
  '47.99A': { label: 'Vente à domicile', classe: '47.99' },
  '47.99B': { label: 'Vente par automates et autres commerces de détail hors magasin, éventaires ou marchés n.c.a.', classe: '47.99' },

  // Section H - Transports et entreposage
  '49.10Z': { label: 'Transport ferroviaire interurbain de voyageurs', classe: '49.10' },
  '49.20Z': { label: 'Transports ferroviaires de fret', classe: '49.20' },
  '49.31Z': { label: 'Transports urbains et suburbains de voyageurs', classe: '49.31' },
  '49.32Z': { label: 'Transports de voyageurs par taxis', classe: '49.32' },
  '49.39A': { label: 'Transports routiers réguliers de voyageurs', classe: '49.39' },
  '49.39B': { label: 'Autres transports routiers de voyageurs', classe: '49.39' },
  '49.39C': { label: 'Téléphériques et remontées mécaniques', classe: '49.39' },
  '49.41A': { label: 'Transports routiers de fret interurbains', classe: '49.41' },
  '49.41B': { label: 'Transports routiers de fret de proximité', classe: '49.41' },
  '49.41C': { label: 'Location de camions avec chauffeur', classe: '49.41' },
  '49.42Z': { label: 'Services de déménagement', classe: '49.42' },
  '49.50Z': { label: 'Transports par conduites', classe: '49.50' },
  '50.10Z': { label: 'Transports maritimes et côtiers de passagers', classe: '50.10' },
  '50.20Z': { label: 'Transports maritimes et côtiers de fret', classe: '50.20' },
  '50.30Z': { label: 'Transports fluviaux de passagers', classe: '50.30' },
  '50.40Z': { label: 'Transports fluviaux de fret', classe: '50.40' },
  '51.10Z': { label: 'Transports aériens de passagers', classe: '51.10' },
  '51.21Z': { label: 'Transports aériens de fret', classe: '51.21' },
  '51.22Z': { label: 'Transports spatiaux', classe: '51.22' },
  '52.10A': { label: 'Entreposage et stockage frigorifique', classe: '52.10' },
  '52.10B': { label: 'Entreposage et stockage non frigorifique', classe: '52.10' },
  '52.21Z': { label: 'Services auxiliaires des transports terrestres', classe: '52.21' },
  '52.22Z': { label: 'Services auxiliaires des transports par eau', classe: '52.22' },
  '52.23Z': { label: 'Services auxiliaires des transports aériens', classe: '52.23' },
  '52.24A': { label: 'Manutention portuaire', classe: '52.24' },
  '52.24B': { label: 'Manutention non portuaire', classe: '52.24' },
  '52.29A': { label: 'Messagerie, fret express', classe: '52.29' },
  '52.29B': { label: 'Affrètement et organisation des transports', classe: '52.29' },
  '53.10Z': { label: 'Activités de poste dans le cadre d\'une obligation de service universel', classe: '53.10' },
  '53.20Z': { label: 'Autres activités de poste et de courrier', classe: '53.20' },

  // Section I - Hébergement et restauration
  '55.10Z': { label: 'Hôtels et hébergement similaire', classe: '55.10' },
  '55.20Z': { label: 'Hébergement touristique et autre hébergement de courte durée', classe: '55.20' },
  '55.30Z': { label: 'Terrains de camping et parcs pour caravanes ou véhicules de loisirs', classe: '55.30' },
  '55.90Z': { label: 'Autres hébergements', classe: '55.90' },
  '56.10A': { label: 'Restauration traditionnelle', classe: '56.10' },
  '56.10B': { label: 'Cafétérias et autres libres-services', classe: '56.10' },
  '56.10C': { label: 'Restauration de type rapide', classe: '56.10' },
  '56.21Z': { label: 'Services des traiteurs', classe: '56.21' },
  '56.29A': { label: 'Restauration collective sous contrat', classe: '56.29' },
  '56.29B': { label: 'Autres services de restauration n.c.a.', classe: '56.29' },
  '56.30Z': { label: 'Débits de boissons', classe: '56.30' },

  // Section J - Information et communication
  '58.11Z': { label: 'Édition de livres', classe: '58.11' },
  '58.12Z': { label: 'Édition de répertoires et de fichiers d\'adresses', classe: '58.12' },
  '58.13Z': { label: 'Édition de journaux', classe: '58.13' },
  '58.14Z': { label: 'Édition de revues et périodiques', classe: '58.14' },
  '58.19Z': { label: 'Autres activités d\'édition', classe: '58.19' },
  '58.21Z': { label: 'Édition de jeux électroniques', classe: '58.21' },
  '58.29A': { label: 'Édition de logiciels système et de réseau', classe: '58.29' },
  '58.29B': { label: 'Édition de logiciels outils de développement et de langages', classe: '58.29' },
  '58.29C': { label: 'Édition de logiciels applicatifs', classe: '58.29' },
  '59.11A': { label: 'Production de films et de programmes pour la télévision', classe: '59.11' },
  '59.11B': { label: 'Production de films institutionnels et publicitaires', classe: '59.11' },
  '59.11C': { label: 'Production de films pour le cinéma', classe: '59.11' },
  '59.12Z': { label: 'Post-production de films cinématographiques, de vidéo et de programmes de télévision', classe: '59.12' },
  '59.13A': { label: 'Distribution de films cinématographiques', classe: '59.13' },
  '59.13B': { label: 'Édition et distribution vidéo', classe: '59.13' },
  '59.14Z': { label: 'Projection de films cinématographiques', classe: '59.14' },
  '59.20Z': { label: 'Enregistrement sonore et édition musicale', classe: '59.20' },
  '60.10Z': { label: 'Édition et diffusion de programmes radio', classe: '60.10' },
  '60.20A': { label: 'Édition de chaînes généralistes', classe: '60.20' },
  '60.20B': { label: 'Édition de chaînes thématiques', classe: '60.20' },
  '61.10Z': { label: 'Télécommunications filaires', classe: '61.10' },
  '61.20Z': { label: 'Télécommunications sans fil', classe: '61.20' },
  '61.30Z': { label: 'Télécommunications par satellite', classe: '61.30' },
  '61.90Z': { label: 'Autres activités de télécommunication', classe: '61.90' },
  '62.01Z': { label: 'Programmation informatique', classe: '62.01' },
  '62.02A': { label: 'Conseil en systèmes et logiciels informatiques', classe: '62.02' },
  '62.02B': { label: 'Tierce maintenance de systèmes et d\'applications informatiques', classe: '62.02' },
  '62.03Z': { label: 'Gestion d\'installations informatiques', classe: '62.03' },
  '62.09Z': { label: 'Autres activités informatiques', classe: '62.09' },
  '63.11Z': { label: 'Traitement de données, hébergement et activités connexes', classe: '63.11' },
  '63.12Z': { label: 'Portails Internet', classe: '63.12' },
  '63.91Z': { label: 'Activités des agences de presse', classe: '63.91' },
  '63.99Z': { label: 'Autres services d\'information n.c.a.', classe: '63.99' },

  // Section K - Activités financières et d'assurance
  '64.11Z': { label: 'Activités de banque centrale', classe: '64.11' },
  '64.19Z': { label: 'Autres intermédiations monétaires', classe: '64.19' },
  '64.20Z': { label: 'Activités des sociétés holding', classe: '64.20' },
  '64.30Z': { label: 'Fonds de placement et entités financières similaires', classe: '64.30' },
  '64.91Z': { label: 'Crédit-bail', classe: '64.91' },
  '64.92Z': { label: 'Autre distribution de crédit', classe: '64.92' },
  '64.99Z': { label: 'Autres activités des services financiers, hors assurance et caisses de retraite, n.c.a.', classe: '64.99' },
  '65.11Z': { label: 'Assurance vie', classe: '65.11' },
  '65.12Z': { label: 'Autres assurances', classe: '65.12' },
  '65.20Z': { label: 'Réassurance', classe: '65.20' },
  '65.30Z': { label: 'Caisses de retraite', classe: '65.30' },
  '66.11Z': { label: 'Administration de marchés financiers', classe: '66.11' },
  '66.12Z': { label: 'Courtage de valeurs mobilières et de marchandises', classe: '66.12' },
  '66.19A': { label: 'Supports juridiques de gestion de patrimoine mobilier', classe: '66.19' },
  '66.19B': { label: 'Autres activités auxiliaires de services financiers, hors assurance et caisses de retraite, n.c.a.', classe: '66.19' },
  '66.21Z': { label: 'Évaluation des risques et dommages', classe: '66.21' },
  '66.22Z': { label: 'Activités des agents et courtiers d\'assurances', classe: '66.22' },
  '66.29Z': { label: 'Autres activités auxiliaires d\'assurance et de caisses de retraite', classe: '66.29' },
  '66.30Z': { label: 'Gestion de fonds', classe: '66.30' },

  // Section L - Activités immobilières
  '68.10Z': { label: 'Activités des marchands de biens immobiliers', classe: '68.10' },
  '68.20A': { label: 'Location de logements', classe: '68.20' },
  '68.20B': { label: 'Location de terrains et d\'autres biens immobiliers', classe: '68.20' },
  '68.31Z': { label: 'Agences immobilières', classe: '68.31' },
  '68.32A': { label: 'Administration d\'immeubles et autres biens immobiliers', classe: '68.32' },
  '68.32B': { label: 'Supports juridiques de gestion de patrimoine immobilier', classe: '68.32' },

  // Section M - Activités spécialisées, scientifiques et techniques
  '69.10Z': { label: 'Activités juridiques', classe: '69.10' },
  '69.20Z': { label: 'Activités comptables', classe: '69.20' },
  '70.10Z': { label: 'Activités des sièges sociaux', classe: '70.10' },
  '70.21Z': { label: 'Conseil en relations publiques et communication', classe: '70.21' },
  '70.22Z': { label: 'Conseil pour les affaires et autres conseils de gestion', classe: '70.22' },
  '71.11Z': { label: 'Activités d\'architecture', classe: '71.11' },
  '71.12A': { label: 'Activité des géomètres', classe: '71.12' },
  '71.12B': { label: 'Ingénierie, études techniques', classe: '71.12' },
  '71.20A': { label: 'Contrôle technique automobile', classe: '71.20' },
  '71.20B': { label: 'Analyses, essais et inspections techniques', classe: '71.20' },
  '72.11Z': { label: 'Recherche-développement en biotechnologie', classe: '72.11' },
  '72.19Z': { label: 'Recherche-développement en autres sciences physiques et naturelles', classe: '72.19' },
  '72.20Z': { label: 'Recherche-développement en sciences humaines et sociales', classe: '72.20' },
  '73.11Z': { label: 'Activités des agences de publicité', classe: '73.11' },
  '73.12Z': { label: 'Régie publicitaire de médias', classe: '73.12' },
  '73.20Z': { label: 'Études de marché et sondages', classe: '73.20' },
  '74.10Z': { label: 'Activités spécialisées de design', classe: '74.10' },
  '74.20Z': { label: 'Activités photographiques', classe: '74.20' },
  '74.30Z': { label: 'Traduction et interprétation', classe: '74.30' },
  '74.90A': { label: 'Activité des économistes de la construction', classe: '74.90' },
  '74.90B': { label: 'Activités spécialisées, scientifiques et techniques diverses', classe: '74.90' },
  '75.00Z': { label: 'Activités vétérinaires', classe: '75.00' },

  // Section N - Activités de services administratifs et de soutien
  '77.11A': { label: 'Location de courte durée de voitures et de véhicules automobiles légers', classe: '77.11' },
  '77.11B': { label: 'Location de longue durée de voitures et de véhicules automobiles légers', classe: '77.11' },
  '77.12Z': { label: 'Location et location-bail de camions', classe: '77.12' },
  '77.21Z': { label: 'Location et location-bail d\'articles de loisirs et de sport', classe: '77.21' },
  '77.22Z': { label: 'Location de vidéocassettes et disques vidéo', classe: '77.22' },
  '77.29Z': { label: 'Location et location-bail d\'autres biens personnels et domestiques', classe: '77.29' },
  '77.31Z': { label: 'Location et location-bail de machines et équipements agricoles', classe: '77.31' },
  '77.32Z': { label: 'Location et location-bail de machines et équipements pour la construction', classe: '77.32' },
  '77.33Z': { label: 'Location et location-bail de machines de bureau et de matériel informatique', classe: '77.33' },
  '77.34Z': { label: 'Location et location-bail de matériels de transport par eau', classe: '77.34' },
  '77.35Z': { label: 'Location et location-bail de matériels de transport aérien', classe: '77.35' },
  '77.39Z': { label: 'Location et location-bail d\'autres machines, équipements et biens matériels n.c.a.', classe: '77.39' },
  '77.40Z': { label: 'Location-bail de propriété intellectuelle et de produits similaires, à l\'exception des œuvres soumises à copyright', classe: '77.40' },
  '78.10Z': { label: 'Activités des agences de placement de main-d\'œuvre', classe: '78.10' },
  '78.20Z': { label: 'Activités des agences de travail temporaire', classe: '78.20' },
  '78.30Z': { label: 'Autre mise à disposition de ressources humaines', classe: '78.30' },
  '79.11Z': { label: 'Activités des agences de voyage', classe: '79.11' },
  '79.12Z': { label: 'Activités des voyagistes', classe: '79.12' },
  '79.90Z': { label: 'Autres services de réservation et activités connexes', classe: '79.90' },
  '80.10Z': { label: 'Activités de sécurité privée', classe: '80.10' },
  '80.20Z': { label: 'Activités liées aux systèmes de sécurité', classe: '80.20' },
  '80.30Z': { label: 'Activités d\'enquête', classe: '80.30' },
  '81.10Z': { label: 'Activités combinées de soutien lié aux bâtiments', classe: '81.10' },
  '81.21Z': { label: 'Nettoyage courant des bâtiments', classe: '81.21' },
  '81.22Z': { label: 'Autres activités de nettoyage des bâtiments et nettoyage industriel', classe: '81.22' },
  '81.29A': { label: 'Désinfection, désinsectisation, dératisation', classe: '81.29' },
  '81.29B': { label: 'Autres activités de nettoyage n.c.a.', classe: '81.29' },
  '81.30Z': { label: 'Services d\'aménagement paysager', classe: '81.30' },
  '82.11Z': { label: 'Services administratifs combinés de bureau', classe: '82.11' },
  '82.19Z': { label: 'Photocopie, préparation de documents et autres activités spécialisées de soutien de bureau', classe: '82.19' },
  '82.20Z': { label: 'Activités de centres d\'appels', classe: '82.20' },
  '82.30Z': { label: 'Organisation de foires, salons professionnels et congrès', classe: '82.30' },
  '82.91Z': { label: 'Activités des agences de recouvrement de factures et des sociétés d\'information financière sur la clientèle', classe: '82.91' },
  '82.92Z': { label: 'Activités de conditionnement', classe: '82.92' },
  '82.99Z': { label: 'Autres activités de soutien aux entreprises n.c.a.', classe: '82.99' },

  // Section O - Administration publique
  '84.11Z': { label: 'Administration publique générale', classe: '84.11' },
  '84.12Z': { label: 'Administration publique (tutelle) de la santé, de la formation, de la culture et des services sociaux, autre que sécurité sociale', classe: '84.12' },
  '84.13Z': { label: 'Administration publique (tutelle) des activités économiques', classe: '84.13' },
  '84.21Z': { label: 'Affaires étrangères', classe: '84.21' },
  '84.22Z': { label: 'Défense', classe: '84.22' },
  '84.23Z': { label: 'Justice', classe: '84.23' },
  '84.24Z': { label: 'Activités d\'ordre public et de sécurité', classe: '84.24' },
  '84.25Z': { label: 'Services du feu et de secours', classe: '84.25' },
  '84.30A': { label: 'Activités générales de sécurité sociale', classe: '84.30' },
  '84.30B': { label: 'Gestion des retraites complémentaires', classe: '84.30' },
  '84.30C': { label: 'Distribution sociale de revenus', classe: '84.30' },

  // Section P - Enseignement
  '85.10Z': { label: 'Enseignement pré-primaire', classe: '85.10' },
  '85.20Z': { label: 'Enseignement primaire', classe: '85.20' },
  '85.31Z': { label: 'Enseignement secondaire général', classe: '85.31' },
  '85.32Z': { label: 'Enseignement secondaire technique ou professionnel', classe: '85.32' },
  '85.41Z': { label: 'Enseignement post-secondaire non supérieur', classe: '85.41' },
  '85.42Z': { label: 'Enseignement supérieur', classe: '85.42' },
  '85.51Z': { label: 'Enseignement de disciplines sportives et d\'activités de loisirs', classe: '85.51' },
  '85.52Z': { label: 'Enseignement culturel', classe: '85.52' },
  '85.53Z': { label: 'Enseignement de la conduite', classe: '85.53' },
  '85.59A': { label: 'Formation continue d\'adultes', classe: '85.59' },
  '85.59B': { label: 'Autres enseignements', classe: '85.59' },
  '85.60Z': { label: 'Activités de soutien à l\'enseignement', classe: '85.60' },

  // Section Q - Santé humaine et action sociale
  '86.10Z': { label: 'Activités hospitalières', classe: '86.10' },
  '86.21Z': { label: 'Activité des médecins généralistes', classe: '86.21' },
  '86.22A': { label: 'Activités de radiodiagnostic et de radiothérapie', classe: '86.22' },
  '86.22B': { label: 'Activités chirurgicales', classe: '86.22' },
  '86.22C': { label: 'Autres activités des médecins spécialistes', classe: '86.22' },
  '86.23Z': { label: 'Pratique dentaire', classe: '86.23' },
  '86.90A': { label: 'Ambulances', classe: '86.90' },
  '86.90B': { label: 'Laboratoires d\'analyses médicales', classe: '86.90' },
  '86.90C': { label: 'Centres de collecte et banques d\'organes', classe: '86.90' },
  '86.90D': { label: 'Activités des infirmiers et des sages-femmes', classe: '86.90' },
  '86.90E': { label: 'Activités des professionnels de la rééducation, de l\'appareillage et des pédicures-podologues', classe: '86.90' },
  '86.90F': { label: 'Activités de santé humaine non classées ailleurs', classe: '86.90' },
  '87.10A': { label: 'Hébergement médicalisé pour personnes âgées', classe: '87.10' },
  '87.10B': { label: 'Hébergement médicalisé pour enfants handicapés', classe: '87.10' },
  '87.10C': { label: 'Hébergement médicalisé pour adultes handicapés et autre hébergement médicalisé', classe: '87.10' },
  '87.20A': { label: 'Hébergement social pour handicapés mentaux et malades mentaux', classe: '87.20' },
  '87.20B': { label: 'Hébergement social pour toxicomanes', classe: '87.20' },
  '87.30A': { label: 'Hébergement social pour personnes âgées', classe: '87.30' },
  '87.30B': { label: 'Hébergement social pour handicapés physiques', classe: '87.30' },
  '87.90A': { label: 'Hébergement social pour enfants en difficultés', classe: '87.90' },
  '87.90B': { label: 'Hébergement social pour adultes et familles en difficultés et autre hébergement social', classe: '87.90' },
  '88.10A': { label: 'Aide à domicile', classe: '88.10' },
  '88.10B': { label: 'Accueil ou accompagnement sans hébergement d\'adultes handicapés ou de personnes âgées', classe: '88.10' },
  '88.10C': { label: 'Aide par le travail', classe: '88.10' },
  '88.91A': { label: 'Accueil de jeunes enfants', classe: '88.91' },
  '88.91B': { label: 'Accueil ou accompagnement sans hébergement d\'enfants handicapés', classe: '88.91' },
  '88.99A': { label: 'Autre accueil ou accompagnement sans hébergement d\'enfants et d\'adolescents', classe: '88.99' },
  '88.99B': { label: 'Action sociale sans hébergement n.c.a.', classe: '88.99' },

  // Section R - Arts, spectacles et activités récréatives
  '90.01Z': { label: 'Arts du spectacle vivant', classe: '90.01' },
  '90.02Z': { label: 'Activités de soutien au spectacle vivant', classe: '90.02' },
  '90.03A': { label: 'Création artistique relevant des arts plastiques', classe: '90.03' },
  '90.03B': { label: 'Autre création artistique', classe: '90.03' },
  '90.04Z': { label: 'Gestion de salles de spectacles', classe: '90.04' },
  '91.01Z': { label: 'Gestion des bibliothèques et des archives', classe: '91.01' },
  '91.02Z': { label: 'Gestion des musées', classe: '91.02' },
  '91.03Z': { label: 'Gestion des sites et monuments historiques et des attractions touristiques similaires', classe: '91.03' },
  '91.04Z': { label: 'Gestion des jardins botaniques et zoologiques et des réserves naturelles', classe: '91.04' },
  '92.00Z': { label: 'Organisation de jeux de hasard et d\'argent', classe: '92.00' },
  '93.11Z': { label: 'Gestion d\'installations sportives', classe: '93.11' },
  '93.12Z': { label: 'Activités de clubs de sports', classe: '93.12' },
  '93.13Z': { label: 'Activités des centres de culture physique', classe: '93.13' },
  '93.19Z': { label: 'Autres activités liées au sport', classe: '93.19' },
  '93.21Z': { label: 'Activités des parcs d\'attractions et parcs à thèmes', classe: '93.21' },
  '93.29Z': { label: 'Autres activités récréatives et de loisirs', classe: '93.29' },

  // Section S - Autres activités de services
  '94.11Z': { label: 'Activités des organisations patronales et consulaires', classe: '94.11' },
  '94.12Z': { label: 'Activités des organisations professionnelles', classe: '94.12' },
  '94.20Z': { label: 'Activités des syndicats de salariés', classe: '94.20' },
  '94.91Z': { label: 'Activités des organisations religieuses', classe: '94.91' },
  '94.92Z': { label: 'Activités des organisations politiques', classe: '94.92' },
  '94.99Z': { label: 'Autres organisations fonctionnant par adhésion volontaire', classe: '94.99' },
  '95.11Z': { label: 'Réparation d\'ordinateurs et d\'équipements périphériques', classe: '95.11' },
  '95.12Z': { label: 'Réparation d\'équipements de communication', classe: '95.12' },
  '95.21Z': { label: 'Réparation de produits électroniques grand public', classe: '95.21' },
  '95.22Z': { label: 'Réparation d\'appareils électroménagers et d\'équipements pour la maison et le jardin', classe: '95.22' },
  '95.23Z': { label: 'Réparation de chaussures et d\'articles en cuir', classe: '95.23' },
  '95.24Z': { label: 'Réparation de meubles et d\'équipements du foyer', classe: '95.24' },
  '95.25Z': { label: 'Réparation d\'articles d\'horlogerie et de bijouterie', classe: '95.25' },
  '95.29Z': { label: 'Réparation d\'autres biens personnels et domestiques', classe: '95.29' },
  '96.01A': { label: 'Blanchisserie-teinturerie de gros', classe: '96.01' },
  '96.01B': { label: 'Blanchisserie-teinturerie de détail', classe: '96.01' },
  '96.02A': { label: 'Coiffure', classe: '96.02' },
  '96.02B': { label: 'Soins de beauté', classe: '96.02' },
  '96.03Z': { label: 'Services funéraires', classe: '96.03' },
  '96.04Z': { label: 'Entretien corporel', classe: '96.04' },
  '96.09Z': { label: 'Autres services personnels n.c.a.', classe: '96.09' },

  // Section T - Activités des ménages en tant qu'employeurs
  '97.00Z': { label: 'Activités des ménages en tant qu\'employeurs de personnel domestique', classe: '97.00' },
  '98.10Z': { label: 'Activités indifférenciées des ménages en tant que producteurs de biens pour usage propre', classe: '98.10' },
  '98.20Z': { label: 'Activités indifférenciées des ménages en tant que producteurs de services pour usage propre', classe: '98.20' },

  // Section U - Activités extra-territoriales
  '99.00Z': { label: 'Activités des organisations et organismes extraterritoriaux', classe: '99.00' },
};

// Fonction utilitaire pour récupérer le libellé d'une sous-classe
export function getSousClasseLabel(code: string): string {
  return NAF_SOUS_CLASSES[code]?.label || code;
}

// Fonction utilitaire pour récupérer la classe parente d'une sous-classe
export function getClasseFromSousClasse(code: string): string | null {
  return NAF_SOUS_CLASSES[code]?.classe || null;
}
